name: docker-install CI

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    outputs:
      outcome: ${{ job.status }}
    continue-on-error: true
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        os:
          - ubuntu:20.04
          - ubuntu:22.04
          - centos:7
          - quay.io/centos/centos:stream9
        version:
          - "20.10"
          - ""

    steps:
    - uses: actions/checkout@v3
    - name: Shellcheck
      run: make shellcheck
    - name: Check distribution
      run: TEST_IMAGE=${{ matrix.os }} VERSION=${{ matrix.version }} make test

  slack-notification:
    name: Send Slack Notification
    if: ${{ always() }}
    needs: test
    uses: QubitPi/hashicorp-aws/.github/workflows/slack-notification.yml@master
    with:
      job-status: ${{ needs.test.outputs.outcome }}
    secrets:
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
